version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g sst

  pre_build:
    commands:
      - echo "Moving into deploy folder..."
      - cd deploy
      - echo "Installing local dependencies..."
      - npm ci || npm install
      - echo "Debug environment variables:"
      - echo "STAGE=$STAGE"
      - echo "CLUSTER_NAME=$CLUSTER_NAME"
      - echo "SERVICE_NAME=$SERVICE_NAME"

  build:
    commands:
      - echo "Deploying people-api SST app to stage $STAGE"
      - sst deploy --stage=$STAGE --verbose --print-logs
      - echo "Checking service status before waiting..."
      - aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME
      - echo "Waiting for service to become stable (this may take up to 10 minutes)..."
      - timeout 900 aws ecs wait services-stable --cluster $CLUSTER_NAME --services $SERVICE_NAME || (echo "Service stability check timed out or failed. Checking service status..." && aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME && exit 1)
      - echo "Done!"
