// values from Voter table 12/19/2025

const politicalPartyValues = [
  'Alliance',
  'American Independent',
  'American',
  'Anarchist',
  'Bread and Roses',
  'Bull Moose',
  'Christian',
  'Citizens Republican',
  'Citizens',
  'Communist',
  'Conservative',
  'Constitution',
  'Constitutional',
  'Consumer',
  'Declined to State',
  'Democratic',
  'Election judges in Chicago did not indicate ballot party',
  'Federalist',
  'Forward',
  'Free Choice',
  'Freedom',
  'Green Libertarian',
  'Green',
  'Harold Washington Democrat',
  'Harold Washington Republican',
  'Harold Washington',
  'Independence',
  'Independent Democrat',
  'Independent Republican',
  'Individualist',
  'Labor',
  'Liberal',
  'Libertarian',
  'Moderate',
  'Mountain',
  'Natural Law',
  'Natural Party',
  'No Labels',
  'Non-Partisan',
  'Other',
  'Patriot',
  'Peace and Freedom',
  'Peoples',
  'Populist',
  'Progressive',
  'Prohibition',
  'Rainbow',
  'Reform',
  'Registered Independent',
  'Republican',
  'Right to Life',
  'Social Democrat',
  'Socialist Labor',
  'Socialist',
  'Taxpayers',
  'Tea',
  'Unknown',
  'We the People',
  'Whig',
  'Working Family Party',
  "Women's Equality Party",
  "Worker's Party",
]

const educationValues = [
  'Attended But Did Not Complete College Likely',
  'Attended Vocational/Technical School Likely',
  'Completed College Likely',
  'Completed Graduate School Likely',
  'Completed High School Likely',
  'Did Not Complete High School Likely',
  null,
]

const genderValues = ['M', 'F', null]

const homeownerValues = ['Home Owner', 'Probable Home Owner', 'Renter', null]

const businessOwnerValues = [
  'Accountant',
  'Builder',
  'Contractor',
  'Dealer/Retailer/Storekeeper',
  'Distributor/Wholesaler',
  'Funeral Director',
  'Maker/Manufacturer',
  'Owner',
  'Partner',
  'Self-Employed',
  null,
]

const veteranValues = ['Yes', null]

const maritalStatusValues = [
  'Inferred Married',
  'Inferred Single',
  'Married',
  'Single',
  null,
]

const presenceOfChildrenValues = ['Y', 'N', null]

const voterStatusValues = [
  'Super',
  'Likely',
  'Unreliable',
  'Unlikely',
  'First Time',
  'Unknown',
]

const languageCodeValues = [
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Arabic',
  'Armenian',
  'Ashanti',
  'Azeri',
  'Bantu',
  'Basque',
  'Bengali',
  'Bulgarian',
  'Burmese',
  'Chinese',
  'Czech',
  'Danish',
  'Dutch',
  'Dzongha',
  'English',
  'Estonian',
  'Farsi',
  'Finnish',
  'French',
  'Ga',
  'Georgian',
  'German',
  'Greek',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Italian',
  'Japanese',
  'Kazakh',
  'Khmer',
  'Kirghiz',
  'Korean',
  'Laotian',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Moldavian',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Oromo',
  'Pashto',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Samoan',
  'Serbo-Croatian',
  'Sinhalese',
  'Slovakian',
  'Slovenian',
  'Somali',
  'Sotho',
  'Spanish',
  'Swahili',
  'Swazi',
  'Swedish',
  'Tagalog',
  'Tajik',
  'Thai',
  'Tibetan',
  'Tongan',
  'Tswana',
  'Turkish',
  'Turkmeni',
  'Urdu',
  'Uzbeki',
  'Vietnamese',
  'Xhosa',
  'Zulu',
  null,
]

const ethnictGroupsValues = [
  'East and South Asian',
  'European',
  'Hispanic and Portuguese',
  'Likely African-American',
  'Other',
  null,
]

const ethnicDescriptionValues = [
  'Afghan',
  'African or Af-Am Self Reported',
  'Albanian',
  'Aleut',
  'Arab',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerb',
  'Bangladeshi',
  'Basque',
  'Belgian',
  'Bhutanese',
  'Bosnian Muslim',
  'Bulgarian',
  'Byelorussian',
  'Chechnian',
  'Chinese',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch (Netherlands)',
  'English/Welsh',
  'Estonian',
  'Fiji',
  'Filipino',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Greek',
  'Guyana',
  'Hawaiian',
  'Hispanic',
  'Hungarian',
  'Icelandic',
  'Indian/Hindu',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Kazak',
  'Khmer',
  'Kirghiz',
  'Korean',
  'Kurdish',
  'Laotian',
  'Latvian',
  'Likely Af-Am (Modeled)',
  'Lithuanian',
  'Luxembourgian',
  'Macedonian',
  'Malay',
  'Maldivian',
  'Maltese',
  'Manx',
  'Moldavian',
  'Mongolian',
  'Multi-Ethnic',
  'Myanmar (Burmese)',
  'Native American',
  'Nauruan',
  'Nepalese',
  'New Zealand',
  'Norwegian',
  'Pakistani',
  'Papua New Guinea',
  'Persian',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian (omitting former Soviet States)',
  'Scots',
  'Serbian',
  'Slovakian',
  'Slovenian',
  'Sri Lankan',
  'Surinam',
  'Swedish',
  'Swiss',
  'Tajik',
  'Thai',
  'Tibetan',
  'Tonga',
  'Turkish',
  'Turkmenistan',
  'Ukrainian',
  'Unknown Asian',
  'Uzbek',
  'Vietnamese',
  'Western Samoa',
  null,
]
