-- Phase 1: Deploy increased grace period (900s) to handle long-running migrations.
-- This migration is intentionally minimal to succeed with the current 300s grace period.
-- 
-- Next steps after this deploys:
-- 1. The 900s grace period will be active in both environments
-- 2. A follow-up migration can then safely recreate indices with CONCURRENTLY
--
-- Note: Demographic indices from migrations 20250917185213, 20250922154402, and 20250923193257
-- exist in develop (small DB) and may be incomplete in master (large DB, timeouts).
-- They will be properly recreated with CONCURRENTLY in a follow-up migration.
